# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Turn this off for GitHub Pages Error
relative_permalinks: false

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'



url:                 "https://manbearwolf.github.io/"
baseurl:             '/lanyon'
#baseurl:            '/lanyon_site2'

# About/contact
author:
  name:              
  url:               
  email:            

# Custom vars
version: 1.0.0
repo: "/manbearwolf/lanyon"

JEKYLL_ENV: development

# The shortname for your Disqus site to enable comments.
disqus: 

# http://jekyllrb.com/docs/pagination/
paginate: 1
paginate_path: '/blog/page:num/'


plugins: 
  - jekyll-paginate
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji


markdown: kramdown
highlighter: rouge

excerpt_separator: "<!--more-->"

#compress.html
# compress_html:
#   clippings: []
#   comments: []
#   endings: []
#   ignore:
#     envs: []
#   blanklines: false
#   profile: false
#   startings: []



# gist:
#   noscript: false

#analytics_id: